### PR TITLE
Fix Labeler workflow

### LINKED ISSUE #37: Github Actions Labeler not working
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Agrover112/awesome-semantic-search/issues) before creating one.

**Describe the bug**
There seems to be an issue with Github token. Giving HTTP error. Refer the actions tab for more details

### PR DESCRIPTION
**Pull request by radiantly**
Fixes the labeler workflow. Untested, but should work in theory.

Closes #37

### CODE REVIEW

**Comment by Agrover112** [comment]
@radiantly  do I need to setup some secret key?

**Comment by radiantly** [comment]
No, not really.

**Comment by Agrover112** [comment]
> No, not really.

Do you mind raising a test PR/Issue after we merge this to see if it works?

**Comment by radiantly** [comment]
Sure, I could open a test PR to see if all works well.

**Pull request merged**
